[package]
name = "aespresso"
version = "0.2.1"
authors = ["Justin Woodring <jwoodrg@gmail.com>"]
edition = "2024"
rust-version = "1.85"
description = "A GTK4 frontend for Arch Linux's archlinux-java script. Requires polkit (pkexec) or lxqt-sudo."
repository = "https://github.com/JustinWoodring/aespresso"
keywords = ["archlinux", "gui", "gtk", "settings", "java"]
license = "BSD-2-Clause"

[dependencies]
gtk = { version = "0.9", package = "gtk4" }

[profile.release]
lto = true
strip = true
